- name: 收集信息
  setup:

# 可选，用于设置静态IP
# - name: 编辑 ens33 配置
#   block:
#     - lineinfile:
#         path: /etc/sysconfig/network-scripts/ifcfg-ens33
#         regexp: '^BOOTPROTO=.*'
#         line: 'BOOTPROTO=static'
#     - blockinfile:
#         path: /etc/sysconfig/network-scripts/ifcfg-ens33
#         block: |
#           NETMASK=255.255.255.0
#           GATEWAY=192.168.43.2
#           DNS1=8.8.8.8
#           DNS2=114.114.114.114
#           IPADDR={{ ansible_default_ipv4['address'] }}
#     - service:
#         name: network
#         state: restarted
#   become: yes

- name: 安装实用工具
  yum: 
    name: 
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
      - sshpass
      - ntpdate
      - ipset
      - ipvsadm
    state: latest

- name: 停止并禁用 firewalld 和 SELinux
  block:
    - service:
        name: firewalld
        state: stopped
        enabled: no
    - lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        line: 'SELINUX=disabled'
    - command: setenforce 0
  become: yes
  ignore_errors: yes

- name: 停止并禁用交换
  shell: |
    swapoff -a  
    sed -ri 's/.*swap.*/#&/' /etc/fstab

- name: 编辑 /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: 设置主机名
  become: yes
  shell: hostnamectl set-hostname {{ inventory_hostname }}

- name: 同步时间
  shell: ntpdate ntp.aliyun.com

- name: 创建 ipvs.modules
  copy:
    dest: /etc/sysconfig/modules/ipvs.modules
    content: |
      #!/bin/bash
      modprobe -- ip_vs
      modprobe -- ip_vs_rr
      modprobe -- ip_vs_wrr
      modprobe -- ip_vs_sh
      modprobe -- nf_conntrack_ipv4
    mode: '0755'

- name: 执行 ipvs.modules
  command: bash /etc/sysconfig/modules/ipvs.modules

- name: 创建 k8s.conf 以加载模块
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: 加载 overlay 和 br_netfilter 模块
  command: modprobe {{ item }}
  with_items:
    - overlay
    - br_netfilter

- name: 创建 k8s.conf 以配置 sysctl 设置
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: 应用 sysctl 设置
  command: sysctl --system
